### PR TITLE
add support for ssl connection using p12 file

### PR DESCRIPTION
**Pull request by simonykq**
Add support to allow SSL/TLS connection over AMQP channel using p12 configuration file. Adding the following options when calling **MarchHare.connect** to enable ssl/tls connection

**tls/ssl** The name of the protocal. For instance: TLSv1.2 etc.
**keycert** The location of p12 file(PKCS #12 store), which contains both the key and certificate for the clint
**password** The password of the p12 file provided above

### CODE REVIEW

**Comment by michaelklishin** [comment]
@aetherknight I'm aware of the key format difference. My point is, we should keep option names as close as possible. Currently this PR introduces a bunch of options that are pretty much independently named.

**Comment by michaelklishin** [comment]
@simonykq if you update option names to be closer to Bunny, I'd be happy to merge this. If you aren't interested or have no time to do so, please state so and I'll get on it myself. Thank you!

**Comment by simonykq** [comment]
@michaelklishin Hi,  According to what I have read in Bunny Gem, should I use **tls_key_cert** or  **ssl_key_cert** or **tls_key_cert_path** or **ssl_key_cert_path** or **ssl_key_certificate_path** or **tls_key_certificate_path** as the option names for passing the p12 file?

**Comment by simonykq** [comment]
and both **cert_password**, **certificate_password** options names for passing the password option for that p12 file?

**Comment by michaelklishin** [comment]
@simonykq please see "Connecting to RabbitMQ from Bunny Using TLS/SSL" in [Bunny's TLS guide](http://rubybunny.info/articles/tls.html). Note that Bunny has to support several aliases for backwards compatibility, don't worry about that too much. As for passwords, `:tls_cert_password` seems natural to me if we go with the `:tls_cert` option.

Thank you!

**Comment by michaelklishin** [comment]
I see that you've updated the PR to support several aliases. Perfect. Thank you very much!

**Pull request merged**
